// Generated by https://quicktype.io

export interface Category {
  type: string;
  id: string;
  updated_at: string;
  created_at: string;
  version: number;
  is_deleted: boolean;
  catalog_v1_ids: CatalogV1ID[];
  present_at_all_locations: boolean;
  category_data: CategoryData;
}

export interface CatalogV1ID {
  catalog_v1_id: string;
  location_id: string;
}

export interface CategoryData {
  name: string;
  ordinal: number;
}
