// Generated by https://quicktype.io

export interface SquareEvent {
  merchant_id: string;
  type: string;
  event_id: string;
  created_at: string;
  data: Data;
}

export interface Data {
  type: string;
  id: string;
  object: Object;
}

export interface Object {
  order_fulfillment_updated?: OrderFulfillmentUpdated;
  order_updated?: OrderUpdated;
}

export interface OrderFulfillmentUpdated {
  created_at: string;
  fulfillment_update: FulfillmentUpdate[];
  location_id: string;
  order_id: string;
  state: string;
  updated_at: string;
  version: number;
}

export interface FulfillmentUpdate {
  fulfillment_uid: string;
  new_state: string;
  old_state: string;
}

export interface OrderUpdated {
  created_at: string;
  location_id: string;
  state: string;
  order_id: string;
  version: number;
  updated_at: string;
}
