import "../styles/globals.css";
import "../styles/widget.min.css";
import Header from "../components/Header/Header";
import Script from "next/script";
import Head from "next/head";
import { Toaster } from "react-hot-toast";
import Context from "../context/Context";

import { PaymentForm } from "react-square-web-payments-sdk";

function MyApp({ Component, pageProps }) {
  return (
    <PaymentForm
      applicationId={process.env.NEXT_PUBLIC_SQUARE_APP_ID}
      locationId="LNW290H2QTZVK"
      cardTokenizeResponseReceived={async (token, buyer) => {
        const response = await fetch("/api/pay", {
          method: "POST",
          headers: {
            "Content-type": "application/json",
          },
          body: JSON.stringify({
            sourceId: token.token,
            amount: 150,
          }),
        });
        //alert(JSON.stringify(await response.json(), null, 2));
      }}
    >
      <Context>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Script
          strategy="afterInteractive"
          defer
          src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}`}
        />

        <Script strategy="afterInteractive" defer>
          {`
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', '${process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS}', {
    page_path: window.location.pathname,
    });
`}
        </Script>

        <div className="max-w-screen min-h-[150vh] bg-bg-tan bg-cover ">
          <Header />
          <Component {...pageProps} />
          <Toaster position="top-right" reverseOrder={false} />
        </div>
      </Context>
    </PaymentForm>
  );
}

export default MyApp;
